### ISSUE TITLE
Kohde alue get_regionkey funktioon

### ISSUE THREAD

**Issue by jhuovari** [pttry/statficlassifications#4]
get_regionkey:ssä voisi olla valinta kohde alueelle, niin ettei tule turhaan mukaan kaikkia aluejakoja.

**Comment by jalasalmi** [comment]
Joo, ajattelin aluksi että sitä käyttäisi yhdessä dplyr::select function kanssa. Mutta totta, kyllä se valinta voisi olla get_regionkeyssäkin. Tai ehkä oma wrapper funktio joka tuo alueita dataan.

**Comment by jalasalmi** [comment]
get_regionkey on nyt paljon joustavampi, source-argumentti määrää pienimmän aluejaon joka avaimeen tulee ja targets-argumenttiin voi laittaa vektorin, jossa halutut kohdealueet.

Lisäsin pakettiin myös add_region-funktion, jolla pystyy vielä nopeammin lisäämään haluttuja alueita dataan. Mutta get_regionkey() left_joinin kanssa ois varmaan selkein ja robustein käytäntö.
