### ISSUE TITLE
Yleisimmin käytetyt avaimet pakettiin valmiiksi, jotta toimii myös offline.

### ISSUE THREAD

**Issue by jalasalmi** [pttry/statficlassifications#5]
Funktiot voisivat ensin tarkistaa, onko internet-yhteyttä. Jos ei ole niin koettaisi hakea avaimen paketin omasta datasta.

**Comment by jhuovari** [comment]
Joo, tämä hyvä. Ja se voisi olla jopa niin, että defaultina hakee omasta. Netistä hakeminen kuitenkin hidastaa koodia ja luokitukset muuttuvat noin kerran vuodessa.

**Comment by jalasalmi** [comment]
Ensimmäinen iteraatio valmis, get_regionkey hakee nyt defaulttina avaimen paketin omasta datasta. 

Vielä täytyy kehitellä mekanismi, jolla käyttäjä saa varoituksen, jos tallennettu avain ei ole datalle sopiva, esim väärä vuosi.
